#!/usr/bin/env bash

OS=$(uname)
HOSTARCH=$(uname -m)

if [ ! -n "$FETCH" ]; then
    FETCH=1
fi

if [ ! -n "$GNU_FTP" ]; then
    GNU_FTP="ftp://ftp.gnu.org/gnu"
fi

if [ ! -n "$ARCHES" ]; then
    echo need to specify architectures to build in the ARCHES environment variable
    echo ie. ARCHES=\"arm sh\"
    exit 1
fi


if [ ! -n "$PREFIX" ]; then
    PREFIX="/usr/local"
fi


if [ -e "$PREFIX" ] && [ ! -d "$PREFIX" ]; then
    echo Install prefix $PREFIX is a non-directory
    exit 1
elif [ ! -e "$PREFIX" ]; then
    if mkdir -p "$PREFIX"; then
        :
    else
        echo Unable to make prefix $PREFIX
        exit 1
    fi
fi

if [ ! -n $PARALLEL ]; then 
    if [ "$OS" = "Linux" ]; then
        COUNT=$(grep processor /proc/cpuinfo | wc -l)
        PARALLEL=-j$(expr $COUNT + $COUNT)
    else
        PARALLEL=-j8
    fi
fi

if [ "$OS" = "Darwin" ]; then
    export CPPFLAGS=-I/opt/local/include
    export LDFLAGS=-L/opt/local/lib
fi
if [ "$OS" = "FreeBSD" ]; then
    export CPPFLAGS=-I/usr/local/include
    export LDFLAGS=-L/usr/local/lib
fi

if [ ! -n "$MAKE" ]; then
    MAKE=make
    if [ "$OS" = "FreeBSD" ]; then
        MAKE=gmake
    fi
fi

if [ "$HOSTARCH" = "amd64" ]; then
    HOSTARCH=x86_64
fi

# load GCCVER and BINVER
. toolvers

if [ "$FETCH" = "1" ]; then
    if [ ! -f binutils-$BINVER.tar.bz2 ]; then
        wget -N $GNU_FTP/binutils/binutils-$BINVER.tar.bz2
    fi
    if [ ! -f gcc-$GCCVER.tar.bz2 ]; then
        wget -N $GNU_FTP/gcc/gcc-$GCCVER/gcc-$GCCVER.tar.bz2
    fi
    if [ ! -f gdb-$GDBVER.tar.bz2 ]; then
        wget -N $GNU_FTP/gdb/gdb-$GDBVER.tar.bz2
    fi
    if [ ! -f mpfr-$MPFRVER.tar.bz2 ]; then
        wget -N $GNU_FTP/mpfr/mpfr-$MPFRVER.tar.bz2
    fi
    if [ ! -f mpc-$MPCVER.tar.gz ]; then
        wget -N $GNU_FTP/mpc/mpc-$MPCVER.tar.gz
    fi
    if [ ! -f gmp-$GMPVER.tar.bz2 ]; then
        wget -N $GNU_FTP/gmp/gmp-$GMPVER.tar.bz2
    fi
fi

function extract-tool()
{
    #echo "extract-tool " $1 $2 $3 $4

    TARFILE=${1}-${2}.tar$3
    TARGETDIR=${1}-${2}
    if [ -f ${TARGETDIR}/.extracted ]; then
        echo "$TARFILE already extracted into $TARGETDIR, skipping"
        return 0
    fi
    if [ ! -f $TARFILE ]; then
        echo "error, missing $TARFILE"
        echo "Set FETCH=1 to fetch automatically"
        exit 1
    fi

    echo extracting $TARFILE
    rm -rf $TARGETDIR
    tar xf $TARFILE || exit 1

    if [ ! -z "$4" ]; then
        echo patching $1
        patch -d $TARGETDIR -p1 < $4 || exit 1
    fi

    touch $TARGETDIR/.extracted || exit 1
}

if [ ! -f .extracted-stamp ]; then
    extract-tool binutils $BINVER .bz2 binutils-patch.txt
    extract-tool gcc $GCCVER .bz2 gcc-patch.txt
    extract-tool gdb $GDBVER .bz2 gdb-patch.txt
    extract-tool gmp $GMPVER .bz2
    extract-tool mpc $MPCVER .gz
    extract-tool mpfr $MPFRVER .bz2
    touch .extracted-stamp
fi

# link the last three libs into gcc
pushd gcc-$GCCVER
ln -sf ../gmp-$GMPVER gmp
ln -sf ../mpc-$MPCVER mpc
ln -sf ../mpfr-$MPFRVER mpfr
popd

for ARCH in $ARCHES; do
    echo "== Doing build for $ARCH"
    if [ "$ARCH" == "arm" ]; then
        TARGET=arm-eabi
    else
        TARGET=$ARCH-elf
    fi

    BINBUILDPATH=build-binutils-$BINVER-$ARCH-$OS-$HOSTARCH
    GCCBUILDPATH=build-gcc-$GCCVER-$ARCH-$OS-$HOSTARCH
    GDBBUILDPATH=build-gdb-$GDBVER-$ARCH-$OS-$HOSTARCH
    export PATH=$INSTALLPATH/bin:$PATH

    if [ ! -f $BINBUILDPATH/built.txt ]; then
        echo "- Binutils..."
        mkdir -p $BINBUILDPATH || exit 1
        pushd $BINBUILDPATH
        if [ ! -f Makefile ]; then
            ../binutils-$BINVER/configure --target=$TARGET --prefix=$PREFIX --disable-werror
        fi
        $MAKE $PARALLEL &&
        $MAKE install &&
        touch built.txt || exit 1
        popd
    fi

    if [ ! -f $GCCBUILDPATH/built.txt ]; then
        echo "- GCC..."
        ARCH_OPTIONS=
        if [ $ARCH == "arm" ]; then
            ARCH_OPTIONS="--with-cpu=arm926ej-s --with-fpu=vfp"
        fi
        mkdir -p $GCCBUILDPATH || exit 1
        pushd $GCCBUILDPATH
        if [ ! -f Makefile ]; then
            ../gcc-$GCCVER/configure --target=$TARGET --prefix=$PREFIX --enable-languages=c,c++ $ARCH_OPTIONS --disable-werror || exit 1
        fi
        $MAKE all-gcc $PARALLEL &&
        $MAKE all-target-libgcc $PARALLEL &&
        $MAKE install-gcc &&
        $MAKE install-target-libgcc &&
        touch built.txt || exit 1
        popd
    fi

    if [ ! -f $GDBBUILDPATH/built.txt ]; then
        echo "- GDB..."
        mkdir -p $GDBBUILDPATH || exit 1
        pushd $GDBBUILDPATH
        if [ ! -f Makefile ]; then
            ../gdb-$GDBVER/configure --target=$TARGET --prefix=$PREFIX --disable-werror || exit 1
        fi
        make $PARALLEL &&
        make install &&
        touch built.txt || exit 1
        popd
    fi
done
